# bc250-vcn-driver v0.1.0 - https://github.com/Kai/bc250-vcn-driver
PACKAGE_NAME="bc250-audio-fix"
PACKAGE_VERSION="0.1.0"
CLEAN="make clean"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="bc250_audio_fix"
DEST_MODULE_LOCATION[0]="/kernel/drivers/sound"
AUTOINSTALL="yes"
